/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as EventsRouteImport } from './routes/Events'
import { Route as EditEventRouteImport } from './routes/EditEvent'
import { Route as AdminRouteImport } from './routes/Admin'
import { Route as AddEventRouteImport } from './routes/AddEvent'
import { Route as IndexRouteImport } from './routes/index'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/Events',
  path: '/Events',
  getParentRoute: () => rootRouteImport,
} as any)
const EditEventRoute = EditEventRouteImport.update({
  id: '/EditEvent',
  path: '/EditEvent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddEventRoute = AddEventRouteImport.update({
  id: '/AddEvent',
  path: '/AddEvent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AddEvent': typeof AddEventRoute
  '/Admin': typeof AdminRoute
  '/EditEvent': typeof EditEventRoute
  '/Events': typeof EventsRoute
  '/Login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AddEvent': typeof AddEventRoute
  '/Admin': typeof AdminRoute
  '/EditEvent': typeof EditEventRoute
  '/Events': typeof EventsRoute
  '/Login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AddEvent': typeof AddEventRoute
  '/Admin': typeof AdminRoute
  '/EditEvent': typeof EditEventRoute
  '/Events': typeof EventsRoute
  '/Login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AddEvent'
    | '/Admin'
    | '/EditEvent'
    | '/Events'
    | '/Login'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AddEvent'
    | '/Admin'
    | '/EditEvent'
    | '/Events'
    | '/Login'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/AddEvent'
    | '/Admin'
    | '/EditEvent'
    | '/Events'
    | '/Login'
    | '/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddEventRoute: typeof AddEventRoute
  AdminRoute: typeof AdminRoute
  EditEventRoute: typeof EditEventRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  DashboardRoute: typeof DashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Events': {
      id: '/Events'
      path: '/Events'
      fullPath: '/Events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/EditEvent': {
      id: '/EditEvent'
      path: '/EditEvent'
      fullPath: '/EditEvent'
      preLoaderRoute: typeof EditEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AddEvent': {
      id: '/AddEvent'
      path: '/AddEvent'
      fullPath: '/AddEvent'
      preLoaderRoute: typeof AddEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddEventRoute: AddEventRoute,
  AdminRoute: AdminRoute,
  EditEventRoute: EditEventRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
